title: ROG Ally X Performance Overlay
description: >-
  PerformanceOverlay fork for custom ROG Ally X usage.
baseurl: ""
url: https://github.com/nicklavoie/steam-deck-tools
github_username: nicklavoie
repository: nicklavoie/steam-deck-tools

include:
  - _redirects

theme: jekyll-theme-primer
plugins:
  #- jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-titles-from-headings
  - jekyll-relative-links
  - jekyll-default-layout
